apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-connections
  name: svc-api-connections
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    service: api-connections
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api-connections
  name: api-connections
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api-connections
  template:
    metadata:
      labels:
        service: api-connections
    spec:
      containers:
      - image: jasonwee/udaconnect-connection:latest
        name: udaconnect-person
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-connections-map
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-connections-map
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-connections-map
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-connections-map
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: PERSON_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: db-connections-map
              key: PERSON_SERVICE_ENDPOINT
      restartPolicy: Always
