{
 "title": "my dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "frontend-service uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{endpoint=\"frontend\",job=\"frontend-service\"}"
    }
   ]
  },
  {
   "title": "frontend-service uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{endpoint=\"frontend\",job=\"frontend-service\"}"
    }
   ]
  },
  {
   "title": "frontend 4xx and 5xx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "flask_http_request_total{status=~\"4.*\", service=\"frontend-service\"}"
    },
    {
     "expr": "flask_http_request_total{status=~\"5.*\", service=\"frontend-service\"}"
    }
   ]
  },
  {
   "title": "frontend 5xx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "flask_http_request_total{status=~\"5.*\", service=\"frontend-service\"}"
    }
   ]
  },
  {
   "title": "backend-service 4xx and 5xx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "flask_http_request_total{status=~\"4.*\",service=\"backend-service\"}"
    },
    {
     "expr": "flask_http_request_total{status=~\"5.*\",service=\"backend-service\"}"
    }
   ]
  }
 ]
}