apiVersion: v1
kind: Service
metadata:
  labels:
    service: svc-api-person
  name: svc-api-person
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    service: svc-api-person
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: svc-api-person
  name: api-deployment-person
spec:
  replicas: 1
  selector:
    matchLabels:
      service: svc-api-person
  template:
    metadata:
      labels:
        service: svc-api-person
    spec:
      containers:
      - image: jasonwee/udaconnect-person:latest
        name: udaconnect-person
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
      restartPolicy: Always
