apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  namespace: prod
spec:
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30040
  type: NodePort
